import { UserProgress, Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  // 1-25: Level Milestones
  {
    id: 'first_win',
    title: 'First Pour',
    description: 'Complete Level 1',
    reward: 50,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.levelsCompleted >= 1,
  },
  {
    id: 'level_5',
    title: 'Chemist Apprentice',
    description: 'Complete 5 levels',
    reward: 100,
    iconName: 'Award',
    isUnlocked: (p) => p.stats.levelsCompleted >= 5,
  },
  {
    id: 'level_10',
    title: 'Novice Alchemist',
    description: 'Complete 10 levels',
    reward: 150,
    iconName: 'Award',
    isUnlocked: (p) => p.stats.levelsCompleted >= 10,
  },
  {
    id: 'level_20',
    title: 'Flask Operator',
    description: 'Complete 20 levels',
    reward: 200,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.levelsCompleted >= 20,
  },
  {
    id: 'level_30',
    title: 'Liquid Sorcerer',
    description: 'Complete 30 levels',
    reward: 250,
    iconName: 'Zap',
    isUnlocked: (p) => p.stats.levelsCompleted >= 30,
  },
  {
    id: 'level_40',
    title: 'Spectrum Solver',
    description: 'Complete 40 levels',
    reward: 300,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.levelsCompleted >= 40,
  },
  {
    id: 'level_50',
    title: 'Half-Century Chemist',
    description: 'Complete 50 levels',
    reward: 400,
    iconName: 'Trophy',
    isUnlocked: (p) => p.stats.levelsCompleted >= 50,
  },
  {
    id: 'level_60',
    title: 'Solution Expert',
    description: 'Complete 60 levels',
    reward: 450,
    iconName: 'Award',
    isUnlocked: (p) => p.stats.levelsCompleted >= 60,
  },
  {
    id: 'level_70',
    title: 'Prism Virtuoso',
    description: 'Complete 70 levels',
    reward: 500,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.levelsCompleted >= 70,
  },
  {
    id: 'level_80',
    title: 'Color Manipulator',
    description: 'Complete 80 levels',
    reward: 550,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.levelsCompleted >= 80,
  },
  {
    id: 'level_90',
    title: 'Alchemy Scholar',
    description: 'Complete 90 levels',
    reward: 600,
    iconName: 'Award',
    isUnlocked: (p) => p.stats.levelsCompleted >= 90,
  },
  {
    id: 'level_100',
    title: 'Centurion Alchemist',
    description: 'Complete 100 levels!',
    reward: 700,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.levelsCompleted >= 100,
  },
  {
    id: 'level_125',
    title: 'Easy Zone Master',
    description: 'Complete 125 levels',
    reward: 800,
    iconName: 'Trophy',
    isUnlocked: (p) => p.stats.levelsCompleted >= 125,
  },
  {
    id: 'level_150',
    title: 'Fluid Tactician',
    description: 'Complete 150 levels',
    reward: 900,
    iconName: 'Zap',
    isUnlocked: (p) => p.stats.levelsCompleted >= 150,
  },
  {
    id: 'level_175',
    title: 'Medium Zone Master',
    description: 'Complete 175 levels',
    reward: 1000,
    iconName: 'Flame',
    isUnlocked: (p) => p.stats.levelsCompleted >= 175,
  },
  {
    id: 'level_200',
    title: 'Color Spectrum Titan',
    description: 'Complete 200 levels',
    reward: 1100,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.levelsCompleted >= 200,
  },
  {
    id: 'level_225',
    title: 'Grand Chemist',
    description: 'Complete 225 levels',
    reward: 1200,
    iconName: 'Trophy',
    isUnlocked: (p) => p.stats.levelsCompleted >= 225,
  },
  {
    id: 'level_250',
    title: 'Hard Zone Sovereign',
    description: 'Complete 250 levels',
    reward: 1300,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.levelsCompleted >= 250,
  },
  {
    id: 'level_275',
    title: 'Laboratory Genius',
    description: 'Complete 275 levels',
    reward: 1400,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.levelsCompleted >= 275,
  },
  {
    id: 'level_300',
    title: 'Element Weaver',
    description: 'Complete 300 levels',
    reward: 1500,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.levelsCompleted >= 300,
  },
  {
    id: 'level_350',
    title: 'Transmutation Master',
    description: 'Complete 350 levels',
    reward: 1750,
    iconName: 'Flame',
    isUnlocked: (p) => p.stats.levelsCompleted >= 350,
  },
  {
    id: 'level_400',
    title: 'Expert Zone Legend',
    description: 'Complete 400 levels',
    reward: 2000,
    iconName: 'Zap',
    isUnlocked: (p) => p.stats.levelsCompleted >= 400,
  },
  {
    id: 'level_450',
    title: 'Master of Solutions',
    description: 'Complete 450 levels',
    reward: 2500,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.levelsCompleted >= 450,
  },
  {
    id: 'level_480',
    title: 'Ultimate Alchemist',
    description: 'Complete 480 levels',
    reward: 3000,
    iconName: 'Trophy',
    isUnlocked: (p) => p.stats.levelsCompleted >= 480,
  },
  {
    id: 'grandmaster_500',
    title: 'Grandmaster Supreme',
    description: 'Complete all 500 levels in the game!',
    reward: 5000,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.levelsCompleted >= 500,
  },

  // 26-45: Difficulty Breakdown Masters
  {
    id: 'easy_5',
    title: 'Easy Beginner',
    description: 'Complete 5 Easy levels',
    reward: 100,
    iconName: 'Award',
    isUnlocked: (p) => (p.stats.easyCompleted || 0) >= 5,
  },
  {
    id: 'easy_10',
    title: 'Easy Explorer',
    description: 'Complete 10 Easy levels',
    reward: 150,
    iconName: 'Award',
    isUnlocked: (p) => (p.stats.easyCompleted || 0) >= 10,
  },
  {
    id: 'easy_25',
    title: 'Easy Scholar',
    description: 'Complete 25 Easy levels',
    reward: 200,
    iconName: 'Sparkles',
    isUnlocked: (p) => (p.stats.easyCompleted || 0) >= 25,
  },
  {
    id: 'easy_50',
    title: 'Easy Veteran',
    description: 'Complete 50 Easy levels',
    reward: 350,
    iconName: 'Trophy',
    isUnlocked: (p) => (p.stats.easyCompleted || 0) >= 50,
  },
  {
    id: 'easy_75',
    title: 'Easy Champion',
    description: 'Complete 75 Easy levels',
    reward: 500,
    iconName: 'Award',
    isUnlocked: (p) => (p.stats.easyCompleted || 0) >= 75,
  },
  {
    id: 'easy_100',
    title: 'Easy Master',
    description: 'Complete 100 Easy levels',
    reward: 700,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.easyCompleted || 0) >= 100,
  },
  {
    id: 'easy_125_complete',
    title: 'Easy Zone Conqueror',
    description: 'Complete all 125 Easy levels!',
    reward: 1000,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.easyCompleted || 0) >= 125,
  },
  {
    id: 'medium_5',
    title: 'Medium Beginner',
    description: 'Complete 5 Medium levels',
    reward: 150,
    iconName: 'Droplets',
    isUnlocked: (p) => (p.stats.mediumCompleted || 0) >= 5,
  },
  {
    id: 'medium_10',
    title: 'Medium Explorer',
    description: 'Complete 10 Medium levels',
    reward: 200,
    iconName: 'Award',
    isUnlocked: (p) => (p.stats.mediumCompleted || 0) >= 10,
  },
  {
    id: 'medium_25',
    title: 'Medium Scholar',
    description: 'Complete 25 Medium levels',
    reward: 300,
    iconName: 'Zap',
    isUnlocked: (p) => (p.stats.mediumCompleted || 0) >= 25,
  },
  {
    id: 'medium_50',
    title: 'Medium Veteran',
    description: 'Complete 50 Medium levels',
    reward: 500,
    iconName: 'Flame',
    isUnlocked: (p) => (p.stats.mediumCompleted || 0) >= 50,
  },
  {
    id: 'medium_75',
    title: 'Medium Master',
    description: 'Complete 75 Medium levels',
    reward: 750,
    iconName: 'Trophy',
    isUnlocked: (p) => (p.stats.mediumCompleted || 0) >= 75,
  },
  {
    id: 'medium_100',
    title: 'Medium Legend',
    description: 'Complete 100 Medium levels',
    reward: 1000,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.mediumCompleted || 0) >= 100,
  },
  {
    id: 'hard_5',
    title: 'Hard Apprentice',
    description: 'Complete 5 Hard levels',
    reward: 200,
    iconName: 'Flame',
    isUnlocked: (p) => (p.stats.hardCompleted || 0) >= 5,
  },
  {
    id: 'hard_15',
    title: 'Hard Veteran',
    description: 'Complete 15 Hard levels',
    reward: 400,
    iconName: 'Flame',
    isUnlocked: (p) => (p.stats.hardCompleted || 0) >= 15,
  },
  {
    id: 'hard_30',
    title: 'Hard Specialist',
    description: 'Complete 30 Hard levels',
    reward: 600,
    iconName: 'Zap',
    isUnlocked: (p) => (p.stats.hardCompleted || 0) >= 30,
  },
  {
    id: 'hard_50',
    title: 'Hard Master',
    description: 'Complete 50 Hard levels',
    reward: 1000,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.hardCompleted || 0) >= 50,
  },
  {
    id: 'expert_5',
    title: 'Expert Initiate',
    description: 'Complete 5 Expert levels',
    reward: 300,
    iconName: 'Zap',
    isUnlocked: (p) => (p.stats.expertCompleted || 0) >= 5,
  },
  {
    id: 'expert_15',
    title: 'Expert Veteran',
    description: 'Complete 15 Expert levels',
    reward: 600,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.expertCompleted || 0) >= 15,
  },
  {
    id: 'expert_25',
    title: 'Expert Overlord',
    description: 'Complete 25 Expert levels',
    reward: 1200,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.expertCompleted || 0) >= 25,
  },

  // 46-60: Perfection & 3-Star Mastery
  {
    id: 'perfect_1',
    title: 'Perfect Start',
    description: 'Get 3 stars on 1 level',
    reward: 50,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.perfectLevels >= 1,
  },
  {
    id: 'perfect_3',
    title: 'Triple Star Triple',
    description: 'Get 3 stars on 3 levels',
    reward: 100,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.perfectLevels >= 3,
  },
  {
    id: 'perfect_5',
    title: 'Star Collector',
    description: 'Get 3 stars on 5 levels',
    reward: 150,
    iconName: 'Award',
    isUnlocked: (p) => p.stats.perfectLevels >= 5,
  },
  {
    id: 'perfect_10',
    title: 'Precision Pourer',
    description: 'Get 3 stars on 10 levels',
    reward: 250,
    iconName: 'Zap',
    isUnlocked: (p) => p.stats.perfectLevels >= 10,
  },
  {
    id: 'perfect_20',
    title: 'Star Enthusiast',
    description: 'Get 3 stars on 20 levels',
    reward: 350,
    iconName: 'Trophy',
    isUnlocked: (p) => p.stats.perfectLevels >= 20,
  },
  {
    id: 'perfect_30',
    title: 'Stellar Chemist',
    description: 'Get 3 stars on 30 levels',
    reward: 450,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.perfectLevels >= 30,
  },
  {
    id: 'perfect_50',
    title: 'Perfectionist Legend',
    description: 'Get 3 stars on 50 levels',
    reward: 600,
    iconName: 'Zap',
    isUnlocked: (p) => p.stats.perfectLevels >= 50,
  },
  {
    id: 'perfect_75',
    title: 'Flawless Flow',
    description: 'Get 3 stars on 75 levels',
    reward: 750,
    iconName: 'Award',
    isUnlocked: (p) => p.stats.perfectLevels >= 75,
  },
  {
    id: 'perfect_100',
    title: 'Perfect Centurion',
    description: 'Get 3 stars on 100 levels',
    reward: 1000,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.perfectLevels >= 100,
  },
  {
    id: 'perfect_150',
    title: 'Stellar Artisan',
    description: 'Get 3 stars on 150 levels',
    reward: 1250,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.perfectLevels >= 150,
  },
  {
    id: 'perfect_200',
    title: 'Perfect Master',
    description: 'Get 3 stars on 200 levels',
    reward: 1500,
    iconName: 'Trophy',
    isUnlocked: (p) => p.stats.perfectLevels >= 200,
  },
  {
    id: 'perfect_250',
    title: 'Flawless Alchemist',
    description: 'Get 3 stars on 250 levels',
    reward: 1800,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.perfectLevels >= 250,
  },
  {
    id: 'perfect_300',
    title: 'Galaxy of Stars',
    description: 'Get 3 stars on 300 levels',
    reward: 2200,
    iconName: 'Sparkles',
    isUnlocked: (p) => p.stats.perfectLevels >= 300,
  },
  {
    id: 'perfect_400',
    title: 'Cosmic Perfectionist',
    description: 'Get 3 stars on 400 levels',
    reward: 3000,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.perfectLevels >= 400,
  },
  {
    id: 'perfect_500',
    title: 'Divine Virtuoso',
    description: 'Get 3 stars on 500 levels!',
    reward: 5000,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.perfectLevels >= 500,
  },

  // 61-72: Flow & Liquid Pours
  {
    id: 'pours_10',
    title: 'First Trickle',
    description: 'Perform 10 liquid pours',
    reward: 50,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 10,
  },
  {
    id: 'pours_25',
    title: 'Steady Stream',
    description: 'Perform 25 liquid pours',
    reward: 75,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 25,
  },
  {
    id: 'pours_50',
    title: 'Fluid Motion',
    description: 'Perform 50 liquid pours',
    reward: 100,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 50,
  },
  {
    id: 'pours_100',
    title: 'Hydrology Initiate',
    description: 'Perform 100 liquid pours',
    reward: 150,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 100,
  },
  {
    id: 'pours_250',
    title: 'Cascade Chemist',
    description: 'Perform 250 liquid pours',
    reward: 250,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 250,
  },
  {
    id: 'pours_500',
    title: 'Master Flow',
    description: 'Perform 500 liquid pours',
    reward: 400,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 500,
  },
  {
    id: 'pours_1000',
    title: 'Ocean of Liquids',
    description: 'Perform 1,000 liquid pours',
    reward: 650,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 1000,
  },
  {
    id: 'pours_2000',
    title: 'Torrential Artisan',
    description: 'Perform 2,000 liquid pours',
    reward: 900,
    iconName: 'Droplets',
    isUnlocked: (p) => p.stats.totalPours >= 2000,
  },
  {
    id: 'pours_3500',
    title: 'Hydro Kinetic',
    description: 'Perform 3,500 liquid pours',
    reward: 1200,
    iconName: 'Zap',
    isUnlocked: (p) => p.stats.totalPours >= 3500,
  },
  {
    id: 'pours_5000',
    title: 'Liquid Dynamo',
    description: 'Perform 5,000 liquid pours',
    reward: 1600,
    iconName: 'Flame',
    isUnlocked: (p) => p.stats.totalPours >= 5000,
  },
  {
    id: 'pours_7500',
    title: 'Maelstrom Solver',
    description: 'Perform 7,500 liquid pours',
    reward: 2000,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.totalPours >= 7500,
  },
  {
    id: 'pours_10000',
    title: 'Tsunami Transmuter',
    description: 'Perform 10,000 liquid pours!',
    reward: 3000,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.totalPours >= 10000,
  },

  // 73-82: Purity & No-Undo Masteries
  {
    id: 'no_undo_1',
    title: 'Steady Hand',
    description: 'Complete 1 level without using Undo',
    reward: 100,
    iconName: 'Sparkles',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 1,
  },
  {
    id: 'no_undo_5',
    title: 'Deterministic Mind',
    description: 'Complete 5 levels without using Undo',
    reward: 200,
    iconName: 'Award',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 5,
  },
  {
    id: 'no_undo_10',
    title: 'Unwavering Focus',
    description: 'Complete 10 levels without using Undo',
    reward: 300,
    iconName: 'Zap',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 10,
  },
  {
    id: 'no_undo_20',
    title: 'Pure Method',
    description: 'Complete 20 levels without using Undo',
    reward: 400,
    iconName: 'Flame',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 20,
  },
  {
    id: 'no_undo_30',
    title: 'Strategic Genius',
    description: 'Complete 30 levels without using Undo',
    reward: 500,
    iconName: 'Trophy',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 30,
  },
  {
    id: 'no_undo_50',
    title: 'Calculated Steps',
    description: 'Complete 50 levels without using Undo',
    reward: 750,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 50,
  },
  {
    id: 'no_undo_75',
    title: 'Flawless Mindset',
    description: 'Complete 75 levels without using Undo',
    reward: 1000,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 75,
  },
  {
    id: 'no_undo_100',
    title: 'Iron Will Legend',
    description: 'Complete 100 levels without using Undo',
    reward: 1500,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.noUndoLevelCompletions || 0) >= 100,
  },
  {
    id: 'undo_10',
    title: 'Time Reversal Apprentice',
    description: 'Use Undo 10 times',
    reward: 100,
    iconName: 'Droplets',
    isUnlocked: (p) => (p.stats.undosUsed || 0) >= 10,
  },
  {
    id: 'undo_50',
    title: 'Time Lord',
    description: 'Use Undo 50 times',
    reward: 250,
    iconName: 'Zap',
    isUnlocked: (p) => (p.stats.undosUsed || 0) >= 50,
  },

  // 83-90: Tactical Boosters & Hints
  {
    id: 'hint_1',
    title: 'Seeking Clarity',
    description: 'Use 1 Hint',
    reward: 50,
    iconName: 'Sparkles',
    isUnlocked: (p) => (p.stats.hintsUsed || 0) >= 1,
  },
  {
    id: 'hint_5',
    title: 'Wise Chemist',
    description: 'Use 5 Hints',
    reward: 100,
    iconName: 'Award',
    isUnlocked: (p) => (p.stats.hintsUsed || 0) >= 5,
  },
  {
    id: 'hint_15',
    title: 'Guided Sorcerer',
    description: 'Use 15 Hints',
    reward: 200,
    iconName: 'Zap',
    isUnlocked: (p) => (p.stats.hintsUsed || 0) >= 15,
  },
  {
    id: 'hint_30',
    title: 'Enlightened Alchemist',
    description: 'Use 30 Hints',
    reward: 350,
    iconName: 'Flame',
    isUnlocked: (p) => (p.stats.hintsUsed || 0) >= 30,
  },
  {
    id: 'hint_50',
    title: 'Oracle of Liquids',
    description: 'Use 50 Hints',
    reward: 500,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.hintsUsed || 0) >= 50,
  },
  {
    id: 'extra_tube_1',
    title: 'Expansionist',
    description: 'Use 1 Extra Tube Booster',
    reward: 100,
    iconName: 'Award',
    isUnlocked: (p) => (p.stats.extraTubesUsed || 0) >= 1,
  },
  {
    id: 'extra_tube_10',
    title: 'Master Builder',
    description: 'Use 10 Extra Tube Boosters',
    reward: 300,
    iconName: 'Trophy',
    isUnlocked: (p) => (p.stats.extraTubesUsed || 0) >= 10,
  },
  {
    id: 'skips_5',
    title: 'Fast Forward Legend',
    description: 'Use 5 Skip Level passes',
    reward: 400,
    iconName: 'Zap',
    isUnlocked: (p) => (p.stats.skipsUsed || 0) >= 5,
  },

  // 91-96: Daily Challenges & Streaks
  {
    id: 'daily_1',
    title: 'Daily Challenger',
    description: 'Complete 1 Daily Challenge',
    reward: 250,
    iconName: 'Sparkles',
    isUnlocked: (p) => (p.dailyChallenge?.totalCompleted || 0) >= 1,
  },
  {
    id: 'daily_3',
    title: 'Daily Scholar',
    description: 'Complete 3 Daily Challenges',
    reward: 400,
    iconName: 'Award',
    isUnlocked: (p) => (p.dailyChallenge?.totalCompleted || 0) >= 3,
  },
  {
    id: 'daily_7',
    title: 'Weekly Warrior',
    description: 'Achieve a 7-day Daily Challenge streak',
    reward: 750,
    iconName: 'Flame',
    isUnlocked: (p) => (p.dailyChallenge?.currentStreak || 0) >= 7,
  },
  {
    id: 'daily_14',
    title: 'Fortnight Alchemist',
    description: 'Complete 14 Daily Challenges',
    reward: 1200,
    iconName: 'Trophy',
    isUnlocked: (p) => (p.dailyChallenge?.totalCompleted || 0) >= 14,
  },
  {
    id: 'daily_30',
    title: 'Monthly Legend',
    description: 'Complete 30 Daily Challenges',
    reward: 2000,
    iconName: 'Crown',
    isUnlocked: (p) => (p.dailyChallenge?.totalCompleted || 0) >= 30,
  },
  {
    id: 'streak_14',
    title: 'Unstoppable Flame',
    description: 'Maintain a 14-day streak',
    reward: 1500,
    iconName: 'Flame',
    isUnlocked: (p) => p.dailyStreak >= 14,
  },

  // 97-100: Economy, Lucky Spin & Customizations
  {
    id: 'lucky_spin_1',
    title: 'Lucky Spinner',
    description: 'Spin the Lucky Wheel 1 time',
    reward: 100,
    iconName: 'Sparkles',
    isUnlocked: (p) => (p.stats.luckySpinsCount || 0) >= 1,
  },
  {
    id: 'lucky_spin_10',
    title: 'Wheel Fortune',
    description: 'Spin the Lucky Wheel 10 times',
    reward: 400,
    iconName: 'Crown',
    isUnlocked: (p) => (p.stats.luckySpinsCount || 0) >= 10,
  },
  {
    id: 'coins_1000',
    title: 'Rich Chemist',
    description: 'Earn a total of 1,000 Coins',
    reward: 200,
    iconName: 'Award',
    isUnlocked: (p) => p.stats.totalCoinsEarned >= 1000,
  },
  {
    id: 'coins_10000',
    title: 'Wealthy Alchemist',
    description: 'Earn a total of 10,000 Coins!',
    reward: 1000,
    iconName: 'Crown',
    isUnlocked: (p) => p.stats.totalCoinsEarned >= 10000,
  },
];

/**
 * Returns list of achievements that are unlocked in userProgress but not yet claimed nor notified.
 */
export function getUnlockedUnclaimedAchievements(progress: UserProgress): Achievement[] {
  return ACHIEVEMENTS.filter(
    (ach) => ach.isUnlocked(progress) && !progress.claimedAchievements.includes(ach.id)
  );
}
