include ':app'

// Auto-include Capacitor plugins if present
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')

include ':capacitor-community-admob'
project(':capacitor-community-admob').projectDir = new File('../node_modules/@capacitor-community/admob/android')
